/**
 * 构建脚本:把 templates 注入源码,用 esbuild 打包成单文件 dist/worker.js
 *
 * 用法: npm run build  (或 node scripts/build.cjs)
 * 产物: dist/worker.js  (部署到 Cloudflare Workers)
 *
 * 注意:首次使用需 npm install (安装 esbuild)。
 */
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const TEMPLATES = path.join(ROOT, 'templates');
const DIST = path.join(ROOT, 'dist');

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

/** 读取并校验规则模板,返回注入用的 base64 */
function rulesB64() {
  // 以二进制读取 gzip 文件
  const gzBytes = fs.readFileSync(path.join(TEMPLATES, 'rules.txt.gz'));
  // 校验是合法 gzip 且能解出规则文本
  const raw = zlib.gunzipSync(gzBytes).toString('utf8');
  console.log(`rules.txt.gz: ${raw.length} chars decompressed`);
  return gzBytes.toString('base64');
}

/** 读取 general 模板,返回注入用的字符串 */
function generalTemplate() {
  const t = read(path.join(TEMPLATES, 'general.txt')).trim();
  console.log(`general.txt: ${t.length} chars`);
  return t.replace(/`/g, '\\`');
}

function build() {
  let esbuild;
  try {
    // eslint-disable-next-line global-require
    esbuild = require('esbuild');
  } catch {
    console.error('[build] esbuild 未安装。请先运行: npm install');
    process.exit(1);
  }

  fs.mkdirSync(DIST, { recursive: true });

  // 注入模板到所有源码文件
  const b64 = rulesB64();
  const gen = generalTemplate();

  // 复制 src/ 到临时构建目录,注入模板
  const buildDir = path.join(DIST, '_build');
  fs.rmSync(buildDir, { force: true, recursive: true });
  fs.cpSync(SRC, buildDir, { recursive: true });

  // 注入 index.js 和 rules.js
  let idxContent = fs.readFileSync(path.join(buildDir, 'index.js'), 'utf8')
    .replace('__GENERAL_TEMPLATE__', gen)
    .replace('__RULES_B64__', b64);
  fs.writeFileSync(path.join(buildDir, 'index.js'), idxContent);

  let rulesContent = fs.readFileSync(path.join(buildDir, 'rules.js'), 'utf8')
    .replace('__RULES_B64__', b64);
  fs.writeFileSync(path.join(buildDir, 'rules.js'), rulesContent);

  const tempEntry = path.join(buildDir, 'index.js');

  const result = esbuild.buildSync({
    entryPoints: [tempEntry],
    bundle: true,
    format: 'esm',
    outfile: path.join(DIST, 'worker.js'),
    platform: 'browser',
    target: 'es2022',
    minify: false,
    sourcemap: false,
    logLevel: 'warning',
    absWorkingDir: ROOT, // 确保相对路径解析正确
    banner: {
      js: '// LX-Sync Surfboard Config Worker\n// Built by scripts/build.cjs — do not edit this file directly.\n// Edit src/ and templates/, then rebuild.\n',
    },
  });

  if (result.errors && result.errors.length) {
    console.error('[build] esbuild 构建失败:', result.errors);
    process.exit(1);
  }

  // 清理临时构建目录
  fs.rmSync(buildDir, { force: true, recursive: true });

  const out = fs.readFileSync(path.join(DIST, 'worker.js'), 'utf8');
  console.log(`dist/worker.js: ${out.length} bytes`);
}

build();