/**
 * 构建脚本:用 esbuild 打包成单文件 dist/worker.js
 *
 * 用法: npm run build  (或 node scripts/build.cjs)
 * 产物: dist/worker.js  (部署到 Cloudflare Workers)
 *
 * 注意:首次使用需 npm install (安装 esbuild)。
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src");
const DIST = path.join(ROOT, "dist");

function build() {
  let esbuild;
  try {
    // eslint-disable-next-line global-require
    esbuild = require("esbuild");
  } catch {
    console.error("[build] esbuild 未安装。请先运行: npm install");
    process.exit(1);
  }

  fs.mkdirSync(DIST, { recursive: true });

  // 复制 src/ 到临时构建目录
  const buildDir = path.join(DIST, "_build");
  fs.rmSync(buildDir, { force: true, recursive: true });
  fs.cpSync(SRC, buildDir, { recursive: true });

  const tempEntry = path.join(buildDir, "index.js");

  const result = esbuild.buildSync({
    entryPoints: [tempEntry],
    bundle: true,
    format: "esm",
    outfile: path.join(DIST, "worker.js"),
    platform: "browser",
    target: "es2022",
    minify: false,
    sourcemap: false,
    logLevel: "warning",
    absWorkingDir: ROOT, // 确保相对路径解析正确
    banner: {
      js: "// Surfboard Composer Worker\n// Built by scripts/build.cjs — do not edit this file directly.\n// Edit src/ and templates/, then rebuild.\n",
    },
  });

  if (result.errors && result.errors.length) {
    console.error("[build] esbuild 构建失败:", result.errors);
    process.exit(1);
  }

  // 清理临时构建目录
  fs.rmSync(buildDir, { force: true, recursive: true });

  const out = fs.readFileSync(path.join(DIST, "worker.js"), "utf8");
  console.log(`dist/worker.js: ${out.length} bytes`);
}

build();
